
trigger:
  branches:
    include:
    - main
    exclude:
    - /*
  paths:  
    exclude:
    - docs/*
    - documents/*
pool:
  vmImage: ubuntu-latest

stages:

  - stage: BUILD
    displayName: Build Docker Image and Helm Chart
    jobs: 
    - job: Building
    variables:
    - group: tftec-app-vars
  - template: stages/stages-build.yml


  - stage: DEPLOY
    condition: succeeded() 
    displayName: Deploy Microservices
    jobs: 
    - job: Deploying
    variables:
    - group: tftec-app-vars
  - template: stages/stages-deploy.yml
